#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Generate the logo CSS file for each logo image in the CDN. Each file will
result in a CSS class like this:

.logo-domain-com {
    background-image: url(http://cdnlogos.cliqz.com/domain.com.png);
}
'''

import sys
import boto


def main(argv):
    c = boto.connect_s3()
    bucket = c.get_bucket('cdnlogos')

    print "/* This file is automatically generated by the getLogoCSS.py script. */"
    print

    for key in bucket.list():
        filename = key.name
        domain = filename.replace(".png", "")
        domain_nodots = domain.replace(".", "-")

        print ".logo-" + domain_nodots + " {"
        print "\tbackground-image: url(http://cdnlogos.cliqz.com/" + \
            filename + ");"
        print "}"


if __name__ == "__main__":
    main(sys.argv)
